name: Deploy to aws EC2 instance 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - uses: actions/checkout@v2

    - name: Fix file permissions
      run: |
        chmod -R 755 .
        find . -type f -exec chmod 644 {} \;

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ubuntu/classroom-notes-temp"
        strip_components: 0

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
        script: |
          # Fix permissions and move files
          sudo chown -R ubuntu:ubuntu /home/ubuntu/classroom-notes-temp
          rm -rf /home/ubuntu/classroom-notes
          mv /home/ubuntu/classroom-notes-temp /home/ubuntu/classroom-notes
          
          # Make scripts executable
          chmod +x /home/ubuntu/classroom-notes/scripts/deploy.sh
          
          # Run deployment
          cd /home/ubuntu/classroom-notes
          ./scripts/deploy.sh 