name: Deploy to aws EC2 instance 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
        script: |
          # Create temp directory
          mkdir -p /home/ubuntu/temp_deploy
          cd /home/ubuntu/temp_deploy
          
          # Clone repository
          git clone https://github.com/anishutrains/livecode.git .
          
          # Create aws_config.py
          cp backend/config/aws_config.template.py backend/config/aws_config.py
          
          # Set permissions
          sudo chown -R ubuntu:ubuntu .
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;
          chmod +x scripts/deploy.sh
          
          # Stop services if they exist
          sudo systemctl stop classroom-notes || true
          sudo systemctl stop nginx || true
          
          # Move to final location
          sudo rm -rf /home/ubuntu/classroom-notes
          sudo mv /home/ubuntu/temp_deploy /home/ubuntu/classroom-notes
          
          # Run deployment script
          cd /home/ubuntu/classroom-notes
          ./scripts/deploy.sh 